"""
Converts a real MVTec test image into a C header file (test_image.h)
that the ESP32 Wokwi sketch (esp32_client.ino) embeds directly into
firmware, as an explicit stand-in for "an image this device captured"
(see esp32_client.ino's docstring for why this isn't a live camera feed).

Usage:
    !python scripts/generate_test_image_header.py \
        --image-path {MVTEC_DIR}/bottle/test/broken_large/001.png \
        --output serving/test_image.h

Wokwi/ESP32 heap constraint, worth knowing before picking an image: a
full-size PNG (tens of KB) embedded as a byte array is fine for flash
storage but will consume real heap when malloc'd into the HTTP request
body (see esp32_client.ino's sendDetectionRequest). Simulated ESP32
boards in Wokwi have limited heap (typically ~200-300KB usable), so an
oversized image could cause the malloc in the sketch to fail. This
script warns if the resulting byte array is large enough to be a
concern, rather than silently producing a header that crashes on
upload.
"""

from __future__ import annotations

import argparse
from pathlib import Path

HEAP_WARNING_THRESHOLD_BYTES = 100_000  # conservative; real ESP32 heap budgets vary by board/config


def generate_header(image_path: Path, output_path: Path, var_name: str = "TEST_IMAGE") -> None:
    image_bytes = image_path.read_bytes()
    size = len(image_bytes)

    if size > HEAP_WARNING_THRESHOLD_BYTES:
        print(
            f"WARNING: {image_path.name} is {size:,} bytes. Wokwi's simulated "
            f"ESP32 typically has limited usable heap; embedding + malloc'ing "
            f"an image this large in sendDetectionRequest() may fail. Consider "
            f"a smaller/more compressed test image if the sketch reports a "
            f"malloc failure."
        )

    lines = [
        "// Auto-generated by scripts/generate_test_image_header.py",
        f"// Source image: {image_path}",
        f"// Size: {size} bytes",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"const uint8_t {var_name}_BYTES[] = {{",
    ]

    hex_bytes = [f"0x{b:02X}" for b in image_bytes]
    for i in range(0, len(hex_bytes), 16):
        lines.append("  " + ", ".join(hex_bytes[i:i + 16]) + ",")

    lines.append("};")
    lines.append(f"const size_t {var_name}_LEN = sizeof({var_name}_BYTES);")
    lines.append("")

    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path} ({size:,} bytes embedded)")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image-path", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    if not args.image_path.exists():
        raise FileNotFoundError(f"No image found at {args.image_path}")

    generate_header(args.image_path, args.output)


if __name__ == "__main__":
    main()