# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nightfall.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'nightfall.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnightfall.proto\x12\tnightfall\"L\n\x0e\x41nomalyRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x14\n\x0cimage_format\x18\x03 \x01(\t\"\x99\x01\n\x0f\x41nomalyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x15\n\ranomaly_score\x18\x03 \x01(\x02\x12\x14\n\x0cis_anomalous\x18\x04 \x01(\x08\x12\x13\n\x0bheatmap_png\x18\x05 \x01(\x0c\x12\x1c\n\x14inference_latency_ms\x18\x06 \x01(\x02\"\x17\n\x15ListCategoriesRequest\",\n\x16ListCategoriesResponse\x12\x12\n\ncategories\x18\x01 \x03(\t2\xb3\x01\n\x12NightfallInference\x12\x46\n\rDetectAnomaly\x12\x19.nightfall.AnomalyRequest\x1a\x1a.nightfall.AnomalyResponse\x12U\n\x0eListCategories\x12 .nightfall.ListCategoriesRequest\x1a!.nightfall.ListCategoriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nightfall_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANOMALYREQUEST']._serialized_start=30
  _globals['_ANOMALYREQUEST']._serialized_end=106
  _globals['_ANOMALYRESPONSE']._serialized_start=109
  _globals['_ANOMALYRESPONSE']._serialized_end=262
  _globals['_LISTCATEGORIESREQUEST']._serialized_start=264
  _globals['_LISTCATEGORIESREQUEST']._serialized_end=287
  _globals['_LISTCATEGORIESRESPONSE']._serialized_start=289
  _globals['_LISTCATEGORIESRESPONSE']._serialized_end=333
  _globals['_NIGHTFALLINFERENCE']._serialized_start=336
  _globals['_NIGHTFALLINFERENCE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
