# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nightfall_pb2 as nightfall__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nightfall_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NightfallInferenceStub:
    """Nightfall anomaly detection inference service.

    Design note: the client must specify `category` explicitly. PatchCore's
    kNN-based scoring has no mechanism to infer which category an image
    belongs to -- there is no classifier in this pipeline, only per-category
    memory banks. Attempting to auto-detect category by scoring against all
    banks and picking the lowest-distance one is unreliable (a wrong-category
    match can spuriously score as "normal") and conflates two different
    problems: category classification and anomaly detection. A real category
    classifier would be a separate, additional model -- noted as a possible
    future addition, not implemented here.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectAnomaly = channel.unary_unary(
                '/nightfall.NightfallInference/DetectAnomaly',
                request_serializer=nightfall__pb2.AnomalyRequest.SerializeToString,
                response_deserializer=nightfall__pb2.AnomalyResponse.FromString,
                _registered_method=True)
        self.ListCategories = channel.unary_unary(
                '/nightfall.NightfallInference/ListCategories',
                request_serializer=nightfall__pb2.ListCategoriesRequest.SerializeToString,
                response_deserializer=nightfall__pb2.ListCategoriesResponse.FromString,
                _registered_method=True)


class NightfallInferenceServicer:
    """Nightfall anomaly detection inference service.

    Design note: the client must specify `category` explicitly. PatchCore's
    kNN-based scoring has no mechanism to infer which category an image
    belongs to -- there is no classifier in this pipeline, only per-category
    memory banks. Attempting to auto-detect category by scoring against all
    banks and picking the lowest-distance one is unreliable (a wrong-category
    match can spuriously score as "normal") and conflates two different
    problems: category classification and anomaly detection. A real category
    classifier would be a separate, additional model -- noted as a possible
    future addition, not implemented here.
    """

    def DetectAnomaly(self, request, context):
        """Score a single image against a specified category's memory bank.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCategories(self, request, context):
        """List categories the server currently has fitted memory banks for,
        so a client can validate its category string before sending images,
        or populate a UI dropdown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NightfallInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectAnomaly': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectAnomaly,
                    request_deserializer=nightfall__pb2.AnomalyRequest.FromString,
                    response_serializer=nightfall__pb2.AnomalyResponse.SerializeToString,
            ),
            'ListCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCategories,
                    request_deserializer=nightfall__pb2.ListCategoriesRequest.FromString,
                    response_serializer=nightfall__pb2.ListCategoriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nightfall.NightfallInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nightfall.NightfallInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NightfallInference:
    """Nightfall anomaly detection inference service.

    Design note: the client must specify `category` explicitly. PatchCore's
    kNN-based scoring has no mechanism to infer which category an image
    belongs to -- there is no classifier in this pipeline, only per-category
    memory banks. Attempting to auto-detect category by scoring against all
    banks and picking the lowest-distance one is unreliable (a wrong-category
    match can spuriously score as "normal") and conflates two different
    problems: category classification and anomaly detection. A real category
    classifier would be a separate, additional model -- noted as a possible
    future addition, not implemented here.
    """

    @staticmethod
    def DetectAnomaly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightfall.NightfallInference/DetectAnomaly',
            nightfall__pb2.AnomalyRequest.SerializeToString,
            nightfall__pb2.AnomalyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightfall.NightfallInference/ListCategories',
            nightfall__pb2.ListCategoriesRequest.SerializeToString,
            nightfall__pb2.ListCategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
